spring:
application:
name: arsoback

datasource:
url: jdbc:mysql://localhost:3306/koala?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
username: root
password: 1234

jpa:
hibernate:
ddl-auto: none
show-sql: true
open-in-view: false
properties:
hibernate:
format_sql: true

springdoc:
api-docs:
enabled: true
swagger-ui:
enabled: true